apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true